### PR TITLE
Create hello_world.java

### PR DESCRIPTION
**Pull request by hms5232**
Hi, i create a hello_world java code.

### CODE REVIEW

**Review by rustiever — CHANGES_REQUESTED** [review]
HI @hms5232 
remove redundant hello world line, 
update the readme file
and lastly one suggestion is read contributing.md file before the contributing

**Comment by hms5232** [comment]
> 
> 
> HI @hms5232
> remove redundant hello world line,
> update the readme file
> and lastly one suggestion is read contributing.md file before the contributing

Sorry for missing README.md updating, it doesn't mention in CONTRIBUTING.md (maybe can update CONTRIBUTING.md about this?). 
I would modify file and push new commit.
Thanks for your reminder.

**Comment by rustiever** [comment]
> > HI @hms5232
> > remove redundant hello world line,
> > update the readme file
> > and lastly one suggestion is read contributing.md file before the contributing
> 
> Sorry for missing README.md updating, it doesn't mention in CONTRIBUTING.md (maybe can update CONTRIBUTING.md about this?).
> I would modify file and push new commit.
> Thanks for your reminder.

yeah sure bro,

**Review by rustiever — APPROVED** [review]
LGTM

**Pull request merged**
