### PR TITLE
jehunseo; hello_world.cpp; Added hello world code

### PR DESCRIPTION
**Pull request by jehunseo**
hello, rustiever!

I added a hello world in Cpp.

Regards, jehunseo

### CODE REVIEW

**Review by rustiever — CHANGES_REQUESTED** [review]
please read the [contributing.md](https://github.com/rustiever/Hello-World/blob/main/CONTRIBUTING.md)

**Review by rustiever — CHANGES_REQUESTED** [review]
Please add official website in file as mentioned in contributing.md file
And these changes looks like a copy pasting from hello_world.c. please do your own work.

**Comment by jehunseo** [comment]
added official(standard) cpp links, and changed comments.

**Review by rustiever — CHANGES_REQUESTED** [review]
Please look at the line number 3
It is got some typos and info related to c language

**Comment by jehunseo** [comment]
sorry for forgot to correct them, now committed it.

**Review by rustiever — APPROVED** [review]
LGTM

**Pull request merged**
