### PR TITLE
jehunseo; hello_world.kt; Added hello world code

### PR DESCRIPTION
**Pull request by jehunseo**
hello, rustiever!
I added Hello world in Kotlin
check out this please, 
regard, jehunseo

### CODE REVIEW

**Review by rustiever — CHANGES_REQUESTED** [review]
please read the [contributing.md](https://github.com/rustiever/Hello-World/blob/main/CONTRIBUTING.md)

**Comment by jehunseo** [comment]
I added commens for hello_world.kt. and #7 too.
I read a contribute.md but i missed checking out example code. I apologize for that.

**Review by rustiever — CHANGES_REQUESTED** [review]
Please add official website in file as mentioned in contributing.md file

**Comment by jehunseo** [comment]
oh, before I understood this to adding 'for info' link.

now i added an official kotlin website link

**Review by rustiever — APPROVED** [review]
LGTM

**Pull request merged**
