### PR TITLE
Create hellow_world.dart

### PR DESCRIPTION
**Pull request by tbsschroeder**
Add hello world in Dart

### CODE REVIEW

**Review by rustiever — CHANGES_REQUESTED** [review]
Hi @tbsschroeder,  file name is incorrect, and please consider the user as newbie, so give something related about main, print etc

**Comment by tbsschroeder** [comment]
@rustiever  thanks! My fingers have been faster than my brain this morning ;-)

**Review by rustiever — APPROVED** [review]
LGTM

**Comment by rustiever** [comment]
@tbsschroeder  please update the readme file

**Pull request merged**
