### PR TITLE
Added Typescript solution of Hello World

### PR DESCRIPTION
**Pull request by hieetesh**
Here's my solution of "Hello World" in Typescript. I have also added the official documentation link and commands to install and execute any typescript code.

### CODE REVIEW

**Review by rustiever — CHANGES_REQUESTED** [review]
Please update in language in readme file

**Comment by hieetesh** [comment]
Sure, I will do that 👍

**Comment by hieetesh** [comment]
Hello @rustiever , I have added Typescript in README file. Also can I do the same in Swift and other languages?

**Review by rustiever — APPROVED** [review]
LGTM

**Comment by rustiever** [comment]
> Hello @rustiever , I have added Typescript in README file. Also can I do the same in Swift and other languages?

Thanks for contributions
You are free to add to more languages but one thing, if possible try to follow alphabetical order while updating the languages in readme file.

**Comment by hieetesh** [comment]
Thank you so much and yes I will follow the alphabetical order :)

**Pull request merged**
