### PR TITLE
Added hello_world.rb

### PR DESCRIPTION
**Pull request by Sha-Kumar**
## Types of changes

- [ ] Bug fix or improving code quality
- [x] New language 
- [ ] New feature
- [x] mention relevent issue number #44 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by rustiever — CHANGES_REQUESTED** [review]
Follow the pull request format please

**Review by rustiever — CHANGES_REQUESTED** [review]
also in readme file Perl language is not in alphabetical order

**Comment by Sha-Kumar** [comment]
Perl I put in such a order by ignoring the cases.
Hence its places before PHP; which I took the naming conventions character type ignorance.

**Comment by Sha-Kumar** [comment]
issue #44

**Review by rustiever — APPROVED** [review]
LGTM

**Pull request merged**
