### PR TITLE
Zentreax; hello_world.py; Added hello world code.

### PR DESCRIPTION
**Pull request by Zentreax**
Hey! 👋 

I added a hello world in Python3.

Regards,

Zentreax

### CODE REVIEW

**Review by rustiever — CHANGES_REQUESTED** [review]
please mention official website as mentioned in [contributing.md](https://github.com/rustiever/Hello-World/blob/main/CONTRIBUTING.md)

**Comment by Zentreax** [comment]
> 
> 
> please mention official website as mentioned in [contributing.md](https://github.com/rustiever/Hello-World/blob/main/CONTRIBUTING.md)

Added.

**Review by rustiever — APPROVED** [review]
LGTM
Thanks for the changes

**Review by rustiever — APPROVED** [review]
LGTM
Thanks for the changes

**Pull request merged**
