### PR TITLE
Added top languages list

### PR DESCRIPTION
**Pull request by adripo**
#1 Updated readme with a list of programming languages

### CODE REVIEW

**Review by rustiever — CHANGES_REQUESTED** [review]
Hi! @adripo , Can you add the hellowold programs to these languages

**Comment by adripo** [comment]
This should be a new issue for every language

**Comment by rustiever** [comment]
> This should be a new issue for every language

then what i feel is creating the issues for each language will be perfect
and why i don't the list coz it will eventually gets added and make the readme file very lengthy.

Just asking  can we do something like scrollable box in markdown file inside where all languages will be there?

**Comment by adripo** [comment]
Sure, I am doing the change

**Comment by adripo** [comment]
@rustiever have a look now. I think it is better.

**Review by rustiever — CHANGES_REQUESTED** [review]
Hi @adripo, excellent work!!!!
Instead of adding top languages add the languages which is in the repo, so newbies will not create duplicate pr's

**Comment by adripo** [comment]
@rustiever Done 👍

**Review by rustiever — APPROVED** [review]
LGTM

**Pull request merged**
